# Default values for ci-manager
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  loadbalancerURL: ""
  airgap: false
replicaCount: 1
maxSurge: 1
maxUnavailable: 0

image:
  registry: docker.io
  repository: harness/ci-manager-signed
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "76019"
  digest: ""

securityImage:
  image:
    registry: docker.io
    repository: harness/sto-plugin
    tag: latest
    digest: ""

waitForInitContainer:
  image:
    registry: docker.io
    repository: harness/helm-init-container
    pullPolicy: IfNotPresent
    tag: "latest"
    digest: ""

ci_images:
  addon:
    registry: docker.io
    digest: ""
    tag: "1.14.7"
    repository: harness/ci-addon

  lite_engine:
    registry: docker.io
    digest: ""
    tag: "1.14.7"
    repository: harness/ci-lite-engine

  git_clone:
    registry: docker.io
    digest: ""
    tag: "1.2.0-rootless"
    repository: harness/drone-git

  kaniko:
    registry: docker.io
    digest: ""
    tag: "1.6.0"
    repository: plugins/kaniko

  kaniko_ecr:
    registry: docker.io
    digest: ""
    tag: "1.6.0"
    repository: plugins/kaniko-ecr

  kaniko_gcr:
    registry: docker.io
    digest: ""
    tag: "1.6.0"
    repository: plugins/kaniko-gcr

  gcs_upload:
    registry: docker.io
    digest: ""
    tag: "1.3.0"
    repository: plugins/gcs

  s3_upload:
    registry: docker.io
    digest: ""
    tag: "1.1.0"
    repository: plugins/s3

  artifactory_upload:
    registry: docker.io
    digest: ""
    tag: "1.1.0"
    repository: plugins/artifactory

  gcs_cache:
    registry: docker.io
    digest: ""
    tag: "1.4.0"
    repository: plugins/cache

  s3_cache:
    registry: docker.io
    digest: ""
    tag: "1.4.0"
    repository: plugins/cache

stoServiceGlobalToken:
  name: harness-secrets
  key: stoAppHarnessToken

mongoSecrets:
  userName:
    name: harness-secrets
    key: mongodbUsername
  password:
    name: mongodb-replicaset-chart
    key: mongodb-root-password

timescaleSecret:
  password:
    name: harness-secrets
    key: timescaledbPostgresPassword

java:
  memory: 4096

appLogLevel: INFO

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "harness-default"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 65534
  runAsNonRoot: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

probes:
  readinessProbe:
    httpGet:
      path: /health
      port: http-ci-manager
    timeoutSeconds: 2
    periodSeconds: 5
    failureThreshold: 5
  livenessProbe:
    httpGet:
      path: /health
      port: http-ci-manager
    timeoutSeconds: 2
    periodSeconds: 10
    failureThreshold: 5
  startupProbe:
    httpGet:
      path: /health
      port: http-ci-manager
    timeoutSeconds: 2
    periodSeconds: 10
    failureThreshold: 25

service:
  type: ClusterIP
  port: 7090
  grpcport: 9979

resources:
  limits:
    cpu: 1
    memory: 8192Mi
  requests:
    cpu: 1
    memory: 1400Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
